# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [1]:
import numpy as np
a = np.arange(15).reshape(3, 5) #arange為NumPy的陣列 #reshape轉換成二維陣列

print('list(a):', list(a)) #將二維的陣列轉換成一維陣列
print('tolist(): ', a.tolist()) #依照多層結構轉換

list(a): [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
tolist():  [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [5]:

a = np.random.randint(10, size=6) 

print(a)
print(a.ndim) #維度
print(a.shape) #大小
print(a.size) #元素
print(a.dtype) #元素的資料型態
print(a.itemsize) #佔用空間
print(len(a)) #長度
print(type(a)) #陣列的資料型態

[3 1 8 8 6 7]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


In [6]:
b = np.random.randint(10, size=(3,4)) 

print(b)
print(b.ndim) #維度
print(b.shape) #大小
print(b.size) #元素
print(b.dtype) #元素的資料型態
print(b.itemsize) #佔用空間
print(len(b)) #長度
print(type(b)) #陣列的資料型態

[[3 5 2 9]
 [6 3 6 7]
 [6 2 0 2]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


In [7]:
c = np.random.randint(10, size=(2,3,2)) 

print(c)
print(c.ndim) #維度
print(c.shape) #大小
print(c.size) #元素
print(c.dtype) #元素的資料型態
print(c.itemsize) #佔用空間
print(len(c)) #長度
print(type(c)) #陣列的資料型態

[[[1 7]
  [8 6]
  [8 1]]

 [[7 6]
  [1 0]
  [2 6]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [9]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))

print(type(list(a.tolist())))
print(type(list(a)))

[6, 7, 2, 9, 4, 3]
[6, 7, 2, 9, 4, 3]
<class 'list'>
<class 'list'>


In [ ]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[array([5, 7, 4, 6]), array([9, 4, 0, 1]), array([9, 1, 2, 9])]


In [ ]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]
[array([[0, 4],
       [0, 1],
       [9, 5]]), array([[8, 7],
       [8, 2],
       [6, 0]])]


In [11]:
def tolist(iterable):
    if type(iterable) != np.ndarray: #如果是多層的話，轉換一次不會改變型態，用if來判斷是否權變更為list
        return iterable
    
    newlist = []
    
    for obj in iterable:             #把所有元素從陣列拉出來，會拉出utem, list
        newlist.append(tolist(obj))  #把元素加進list，並呼叫函式遞迴
    return list(newlist)             #處理完所有的array，變成多層結構list回傳

    #進階版縮寫成 return [tolist(obj) for obj in iterable]

print(tolist(a))
print(tolist(b))
print(tolist(c))

[6, 7, 2, 9, 4, 3]
[[3, 5, 2, 9], [6, 3, 6, 7], [6, 2, 0, 2]]
[[[1, 7], [8, 6], [8, 1]], [[7, 6], [1, 0], [2, 6]]]


[7, 6, 7, 3, 7, 5]
[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]
