# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [1]:
import numpy as np

In [10]:
a = np.arange(1, 12)
a[(a >= 3) & (a <= 6)] *= -1
print(a)

[ 1  2 -3 -4 -5 -6  7  8  9 10 11]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [13]:
A = np.random.rand(3, 6)

print((A[A > 0.5]).size)

[[0.87183283 0.2370553  0.00322661 0.89493781 0.53419281 0.72899166]
 [0.69879598 0.64505969 0.75939338 0.6023804  0.47402865 0.68055328]
 [0.64422592 0.00352215 0.15820581 0.17844379 0.8869391  0.19082959]]
11
